/*
	BU SCRIPT SILVER SCHEMA İÇİN TABLOLARI OLUŞTURUR 
	EĞER TABLOLAR ÖNCEDEN OLUŞTURULMUŞSA İLK ETAPTA ONLARI DROP'LAR
*/
DROP TABLE IF EXISTS SILVER.CRM_CUST_INFO;
CREATE TABLE SILVER.CRM_CUST_INFO (
	CST_ID INT,
	CST_KEY TEXT,
	CST_FIRSTNAME TEXT,
	CST_LASTNAME TEXT,
	CST_MARITAL_STATUS TEXT,
	CST_GNDR TEXT,
	CST_CREATE_DATE DATE,
	DWH_OLUSTURMA_TARIHI TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS SILVER.CRM_PRD_INFO;
CREATE TABLE SILVER.CRM_PRD_INFO (
	prd_id INT,
	cat_id TEXT,
	prd_key TEXT,
	prd_nm TEXT,
	prd_cost INT,
	prd_line TEXT,
	prd_start_dt DATE,
	prd_end_dt DATE,
	DWH_OLUSTURMA_TARIHI TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS SILVER.CRM_PRD_SALES_DETAILS;
CREATE TABLE SILVER.CRM_PRD_SALES_DETAILS (
	sls_ord_num TEXT,
	sls_prd_key TEXT,
	sls_cust_id INT,
	sls_order_dt DATE,
	sls_ship_dt DATE,
	sls_due_dt DATE,
	sls_sales INT,
	sls_quantity INT,
	sls_price INT,
	DWH_OLUSTURMA_TARIHI TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS SILVER.ERP_CUST_AZ12;
CREATE TABLE SILVER.ERP_CUST_AZ12 (
	CID TEXT, 
	BDATE DATE,
	GEN TEXT,
	DWH_OLUSTURMA_TARIHI TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS SILVER.ERP_LOC_A101;
CREATE TABLE SILVER.ERP_LOC_A101 (
	CID TEXT,
	CNTRY TEXT,
	DWH_OLUSTURMA_TARIHI TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS SILVER.ERP_PX_CAT_G1V2;
CREATE TABLE SILVER.ERP_PX_CAT_G1V2 (
	ID TEXT,
	CAT TEXT,
	SUBCAT TEXT,
	MAINTENANCE TEXT,
	DWH_OLUSTURMA_TARIHI TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
